### ISSUE TITLE
Application API Down

### ISSUE THREAD

**Issue by Abhijeet1828** [philipstubbs13/australia-fire-api-and-dashboard#52]
Hi Team, 

Thanks for the beautiful work on these APIs. The API has gone down in the past few days and is still currently down. 
Please let me know if the project will be up again or not, as I have used these APIs in my project. 

Thanks for the help. 
<img width="645" alt="Screen Shot 2022-10-11 at 9 35 40 pm" src="https://user-images.githubusercontent.com/102120061/195068354-205e5d8f-2a04-448a-8f66-e71ef1470440.png">

**Comment by philipstubbs13** [comment]
Hi @Abhijeet1828. Sorry for the late response and for the APIs being down. The application API was previously deployed to heroku using the heroku free plan. Heroku recently got rid of their free plan, which is why the API was down. Because heroku no longer has a free plan, I deployed the application API to render, which does have a free plan option.

To continue using the API in your project, use the following url: https://australia-fire-api-dashboard.onrender.com/api/v1.0/

For example: https://australia-fire-api-dashboard.onrender.com/api/v1.0/fires_time_series

Let me know if you run into any issues. Thanks!
